version: '3'

services:
  docker-angular:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_NAME=myapp
    working_dir: /$APP_NAME
    entrypoint: "env"
    volumes:
      - "$PWD/$APP_NAME:/$APP_NAME"
    ports:
      - "4200:4200"