version: '3'

services:
  docker-angular:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_NAME=myapp
    volumes:
      - "$PWD/myapp:/myapp"
    ports:
      - "4200:4200"